spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaemi-marble
    username: user
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true # (2.5~) Hibernate ??? ?? data.sql ??
