db:
  host: gaemi-db.cnqayuxxifas.ap-northeast-2.rds.amazonaws.com
  port: 3306
  name: gaemidb
  username: admin
  password: Bemax2023!

key: gaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemigaemi