version: '3'
services:
  mysql-local: # Local environment database
    image: mysql:8.0
    container_name: mysql-local
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gaemi-marble
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
